console.time('Your code took')
console.log('Hello console')
console.log(4+34)
console.log(34)
console.log(true)
console.log(true)
console.log([34,2,12,14])
console.log({name:'Rishabh',marks:56})
console.table({name:'Rishabh',marks:65})
console.warn('This is warning')
//console.clear()
console.timeEnd('Your code took')
//console.assert(566<189,"Age > 189 is not possible")
//console.error('This is an error)
